# Generated by Django 4.0.4 on 2022-05-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emaile',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
